# run using `rattler-build build` then upload ./output/noarch/asyncio_for_robotics-1.2.5-pyh4616a5c_0.conda
context:
  version: 1.2.5

package:
  name: asyncio_for_robotics
  version: ${{ version }}

source:
  path: .
  use_gitignore: true 

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
  - python >= 3.10
  - setuptools >= 58.2.0
  - pip
  run:
  - python
  - if: python <= "3.10" 
    then: 
      - typing_extensions
      - async-timeout

tests:
- python:
    imports:
    - asyncio_for_robotics
    - asyncio_for_robotics.core
    - asyncio_for_robotics.core.sub
    - asyncio_for_robotics.core.utils
    - asyncio_for_robotics.textio
    - asyncio_for_robotics.example.custom_stdout
    pip_check: true
    python_version: [
      "3.10.*",
      "3.11.*",
      "3.12.*",
      "3.13.*",
      "3.14.*"]
- script:
    - python3 -m pytest ./tests
  requirements:  
    run:
      - python >= 3.14
      - pytest
      - pytest-asyncio
      - colorama
  files:  
    source:
      - tests/
- script:
    - python3 -m pytest ./tests
  requirements:  
    run:
      - python <= 3.10
      - pytest
      - pytest-asyncio
      - colorama
  files:  
    source:
      - tests/
